### ISSUE TITLE
resolution and nbins as parameters of 'MeDuSA' function

### ISSUE THREAD

**Issue by pptnz** [LeonSong1995/MeDuSA#1]
Hello,

What is the difference between resolution and nbins as parameters of 'MeDuSA' function?

Thank you!

**Comment by LeonSong1995** [comment]
Hello, 

Thanks for using MeDuSA. The 'resolution' parameter is used in the deconvolution process, determining the number of cell state bins in the output. The 'nbins' parameter is employed in the gene selection process, ensuring that the chosen genes are informative for the entire cell trajectory and not biased towards a specific state.

Best,
Liyang

**Comment by pptnz** [comment]
Hi Liyang,

That makes sense! Thank you for your kind explanation.

Best,
Minji
